### ISSUE TITLE
Multi Subnets

### ISSUE THREAD

**Issue by JustoStyle** [samburney/l4usage#7]
Only counting data for one subnet. for example i have entered 192.168.5.0/24 and 192.168.18.0/24 but it only counts .5 unless i move .18 above it. then it counts .18 but doesn't count .5 
it seems like its only counting the first subnet. Single IPs work can have as many singles and they work. Single IPs also work after having the subnet first. seems like the problem is completely related to subnets.

**Comment by samburney** [comment]
Fixed in https://github.com/samburney/mt-ip-accounting/commit/b6d6bcf0ba8d6400e5fffcda6d979e083fadf56e
